language: python
group: travis_latest

git:
  depth: 25
  quiet: true

python:
- 3.6

os:
- linux

install: pip install -e .[tests,cov]

script:
- pytest -rsv
- flake8
- mypy .

after_success:
- pytest --cov
- coveralls