[build-system]
requires = ["setuptools", "wheel",
'python-dateutil', 'pytz','numpy','scipy','h5py', 'astropy',
'pymap3d','sciencedates',
'tifffile','matplotlib','seaborn',
'dascutils','themisasi'
 "nose"] 
